[package]
name = "segmenter-utils-rs"
version = "0.1.0"
authors = ["hikiko4ern"]
edition = "2021"
license = "Unlicense"
publish = false
repository = "https://github.com/hikiko4ern/coub-addons"
rust-version = "1.67.1"
description = "Intl.Segmenter utils based on ICU4X"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = { version = "0.1.7", optional = true }
icu_segmenter = "1.4.0"
itertools = { version = "0.12.1", default-features = false }
js-sys = "0.3.69"
serde = { version = "1.0.197", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
tsify = { version = "0.4.5", default-features = false, features = ["js"] }
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", optional = true }

[features]
default = ["console_panic_hook"]
console_panic_hook = ["console_error_panic_hook", "web-sys/console"]
