version: '3'

set: [pipefail]

tasks:
  segmenter-utils:watch:
    aliases: [su:watch]
    desc: builds `segmenter-utils` in watch mode
    cmds:
      - cargo watch -w packages/segmenter-utils/src -w packages/segmenter-utils/Cargo.toml -w packages/segmenter-utils/Taskfile.yml -w Cargo.lock -w Cargo.toml -s "pnpm su exec task build MODE=dev"
    preconditions:
      - sh: cargo watch -V
        msg: '`cargo-watch` is required (https://lib.rs/crates/cargo-watch)'
